
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "8aefa87c742325052c6f342d09d8153f04dc61d7",
 "version": "v0.5.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
